
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMESexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorfactor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'PLUS':([1,2,3,4,10,11,12,13,14,15,],[-7,-6,6,-3,6,-1,-2,-5,-4,-8,]),'$end':([1,2,3,4,11,12,13,14,15,],[-7,-6,0,-3,-1,-2,-5,-4,-8,]),'DIVIDE':([1,2,4,11,12,13,14,15,],[-7,-6,8,8,8,-5,-4,-8,]),'MINUS':([1,2,3,4,10,11,12,13,14,15,],[-7,-6,7,-3,7,-1,-2,-5,-4,-8,]),'NUMBER':([0,5,6,7,8,9,],[1,1,1,1,1,1,]),'TIMES':([1,2,4,11,12,13,14,15,],[-7,-6,9,9,9,-5,-4,-8,]),'RPAREN':([1,2,4,10,11,12,13,14,15,],[-7,-6,-3,15,-1,-2,-5,-4,-8,]),'LPAREN':([0,5,6,7,8,9,],[5,5,5,5,5,5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'factor':([0,5,6,7,8,9,],[2,2,2,2,13,14,]),'expression':([0,5,],[3,10,]),'term':([0,5,6,7,],[4,4,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser.py',10),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','parser.py',14),
  ('expression -> term','expression',1,'p_expression_term','parser.py',18),
  ('term -> term TIMES factor','term',3,'p_term_times','parser.py',22),
  ('term -> term DIVIDE factor','term',3,'p_term_div','parser.py',26),
  ('term -> factor','term',1,'p_term_factor','parser.py',30),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser.py',34),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',38),
]
