
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEleftLPARENRPARENDIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMESexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorfactor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'PLUS':([2,3,4,5,6,11,12,13,14,15,],[-6,-3,9,-7,9,-8,-4,-5,-1,-2,]),'LPAREN':([0,1,7,8,9,10,],[1,1,1,1,1,1,]),'TIMES':([2,3,5,11,12,13,14,15,],[-6,7,-7,-8,-4,-5,7,7,]),'DIVIDE':([2,3,5,11,12,13,14,15,],[-6,8,-7,-8,-4,-5,8,8,]),'MINUS':([2,3,4,5,6,11,12,13,14,15,],[-6,-3,10,-7,10,-8,-4,-5,-1,-2,]),'RPAREN':([2,3,5,6,11,12,13,14,15,],[-6,-3,-7,11,-8,-4,-5,-1,-2,]),'NUMBER':([0,1,7,8,9,10,],[5,5,5,5,5,5,]),'$end':([2,3,4,5,11,12,13,14,15,],[-6,-3,0,-7,-8,-4,-5,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,1,9,10,],[3,3,14,15,]),'factor':([0,1,7,8,9,10,],[2,2,12,13,2,2,]),'expression':([0,1,],[4,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser.py',28),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','parser.py',33),
  ('expression -> term','expression',1,'p_expression_term','parser.py',38),
  ('term -> term TIMES factor','term',3,'p_term_times','parser.py',43),
  ('term -> term DIVIDE factor','term',3,'p_term_div','parser.py',48),
  ('term -> factor','term',1,'p_term_factor','parser.py',53),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser.py',58),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',63),
]
